# Generated by Django 3.0.4 on 2020-03-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfect', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comtent',
            new_name='content',
        ),
    ]
